name: test-linux

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

  # Run tests once a week on Sunday.
  schedule:
    - cron: "0 6 * * 0"

permissions:
  contents: read

jobs:
  test-linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: |
          sudo apt update
          sudo apt install -y ninja-build
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        run: cmake ${GITHUB_WORKSPACE}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config Release

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -VV
        env:
          CTEST_OUTPUT_ON_FAILURE: True
